# Generated by Django 3.1.7 on 2021-04-14 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210414_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='section',
            name='slug',
        ),
    ]
