# Generated by Django 4.1.6 on 2023-02-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_orderline_email_alter_product_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='email',
        ),
        migrations.AddField(
            model_name='orderline',
            name='name',
            field=models.CharField(max_length=70, null=True, verbose_name='Имя'),
        ),
    ]
