# Generated by Django 4.1.6 on 2023-02-25 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_orderline_email_orderline_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='name',
        ),
        migrations.AddField(
            model_name='orderline',
            name='email',
            field=models.EmailField(default=0, max_length=254, verbose_name=django.db.models.deletion.CASCADE),
        ),
    ]
