# Generated by Django 4.1.6 on 2023-03-02 16:12

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_order_phone_alter_product_ves'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='surname',
            field=models.CharField(max_length=70, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=12, region=None, unique=True, verbose_name='Телефон'),
        ),
    ]
