# Generated by Django 4.1.6 on 2023-03-06 13:14

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_order_surname_alter_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=12, region=None, verbose_name='Телефон'),
        ),
    ]
