# Generated by Django 4.1.6 on 2023-03-08 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_blogpost_blogcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogComment',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
