# Generated by Django 4.1.6 on 2023-03-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='email',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='name',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='review',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='surname',
        ),
        migrations.AlterField(
            model_name='reviews',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
