# Generated by Django 4.1.6 on 2023-03-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_name_delete_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('otziv', models.TextField(blank=True, verbose_name='Отзыв')),
            ],
        ),
        migrations.DeleteModel(
            name='Name',
        ),
    ]
