# Generated by Django 4.1.6 on 2023-03-09 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_review_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='otziv',
            new_name='rev',
        ),
    ]
