# Generated by Django 4.1.6 on 2023-03-12 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_order_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='time',
        ),
    ]
