# Generated by Django 4.1.6 on 2023-03-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_remove_order_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vakancy', models.CharField(max_length=70, verbose_name='Название вакансии')),
                ('opit', models.BooleanField(verbose_name='Требуемый опыт')),
                ('trebovaniya', models.CharField(max_length=70, verbose_name='Требования')),
                ('usloviya', models.CharField(max_length=70, verbose_name='Условия труда')),
                ('zp', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Зарплата')),
            ],
        ),
    ]
