# Generated by Django 4.1.6 on 2023-03-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_job'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AddField(
            model_name='job',
            name='obyazanosti',
            field=models.TextField(max_length=300, null=True, verbose_name='Обязанности'),
        ),
        migrations.AlterField(
            model_name='job',
            name='opit',
            field=models.BooleanField(verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='job',
            name='trebovaniya',
            field=models.TextField(max_length=300, verbose_name='Требования'),
        ),
        migrations.AlterField(
            model_name='job',
            name='usloviya',
            field=models.TextField(max_length=300, verbose_name='Условия труда'),
        ),
    ]
