# Generated by Django 4.1.7 on 2023-03-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_alter_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_delivery',
            field=models.DateTimeField(null=True, verbose_name='Время доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='Телефон'),
        ),
    ]
